name: itunes_search_app
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: '14.x'

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Install Node.js 
          uses: actions/setup-node@v2
          with:
            node-version: ${{ env.NODE_VERSION }}
            
        - name: Install dependencies
          run: npm install
          
        - name: Run tests 
          run: npm test
